# Generated by Django 5.0.6 on 2024-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='beta',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='daily_change',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_yield',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='earnings_yield',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='forward_pe_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='long_business_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_book_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_sales_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week_52_high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week_52_low',
            field=models.FloatField(null=True),
        ),
    ]
